### ISSUE TITLE
Error using mmwave.dsp.compensation.add_doppler_compensation

### ISSUE THREAD

**Issue by CRalli1** [PreSenseRadar/OpenRadar#33]
Hi,
Really useful package! I got an error trying to use this function, I have pasted the error output below. I tried it with and without the num_doppler _bins variable which your docs say is optional and it came up with the same error for both.

Cheers,
Charlie

`Traceback (most recent call last):
  File "Process.py", line 116, in <module>
    R,D,A=processing(F)
  File "Process.py", line 65, in processing
    Frame2=mmc.add_doppler_compensation(Frame,2)
  File "/home/`(path)`/.local/lib/python3.8/site-packages/mmwave/dsp/compensation.py", line 79, in add_doppler_compensation
    azimuth_mod_coefs, bins = _generate_dft_sin_cos_table(int(num_doppler_bins))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

and

`Traceback (most recent call last):
  File "Process.py", line 115, in <module>
    R,D,A=processing(F)
  File "Process.py", line 64, in processing
    Frame2=mmc.add_doppler_compensation(Frame,2,16)
  File "/home/`(path)`/.local/lib/python3.8/site-packages/mmwave/dsp/compensation.py", line 79, in add_doppler_compensation
    azimuth_mod_coefs, bins = _generate_dft_sin_cos_table(int(num_doppler_bins))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

**Comment by yfsun0327** [comment]
Yes. It is a bug. Therefore, you have to provide the num_doppler _bins variable.
